/*
 * This file is part of the OWL API.
 *
 * The contents of this file are subject to the LGPL License, Version 3.0.
 *
 * Copyright (C) 2011, The University of Manchester
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/.
 *
 *
 * Alternatively, the contents of this file may be used under the terms of the Apache License, Version 2.0
 * in which case, the provisions of the Apache License Version 2.0 are applicable instead of those above.
 *
 * Copyright 2011, University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated By:JavaCC: Do not edit this line. TurtleParserConstants.java */
package uk.ac.manchester.cs.owl.owlapi.turtle.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TurtleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int STRING = 8;
  /** RegularExpression Id. */
  int LONG_STRING = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int INTEGER = 13;
  /** RegularExpression Id. */
  int DOUBLE = 14;
  /** RegularExpression Id. */
  int DECIMAL = 15;
  /** RegularExpression Id. */
  int EXPONENT = 16;
  /** RegularExpression Id. */
  int OPENPAR = 17;
  /** RegularExpression Id. */
  int CLOSEPAR = 18;
  /** RegularExpression Id. */
  int OPEN_SQUARE_BRACKET = 19;
  /** RegularExpression Id. */
  int CLOSE_SQUARE_BRACKET = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int DOT = 22;
  /** RegularExpression Id. */
  int SEMICOLON = 23;
  /** RegularExpression Id. */
  int PREFIX = 24;
  /** RegularExpression Id. */
  int DOUBLE_CARET = 25;
  /** RegularExpression Id. */
  int BASE = 26;
  /** RegularExpression Id. */
  int AT = 27;
  /** RegularExpression Id. */
  int A = 28;
  /** RegularExpression Id. */
  int EMPTY_BLANK_NODE = 29;
  /** RegularExpression Id. */
  int NODE_ID_START = 30;
  /** RegularExpression Id. */
  int TRUE = 31;
  /** RegularExpression Id. */
  int FALSE = 32;
  /** RegularExpression Id. */
  int SELECT = 33;
  /** RegularExpression Id. */
  int WHERE = 34;
  /** RegularExpression Id. */
  int FILTER = 35;
  /** RegularExpression Id. */
  int LETTER = 36;
  /** RegularExpression Id. */
  int FULLIRI = 37;
  /** RegularExpression Id. */
  int PNAME_NS = 38;
  /** RegularExpression Id. */
  int PN_LOCAL = 39;
  /** RegularExpression Id. */
  int PNAME_LN = 40;
  /** RegularExpression Id. */
  int PN_PREFIX = 41;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 42;
  /** RegularExpression Id. */
  int PN_CHARS = 43;
  /** RegularExpression Id. */
  int PN_CHARS_U = 44;
  /** RegularExpression Id. */
  int NODEID = 45;
  /** RegularExpression Id. */
  int ERROR = 46;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING = 1;
  /** Lexical state. */
  int IN_LONG_STRING = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"\\\"\"",
    "<token of kind 7>",
    "\"\\\"\"",
    "\"\\\"\\\"\\\"\"",
    "<token of kind 10>",
    "\"\\\"\\\"\\\"\"",
    "<DIGIT>",
    "<INTEGER>",
    "<DOUBLE>",
    "<DECIMAL>",
    "<EXPONENT>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"@prefix\"",
    "\"^^\"",
    "\"@base\"",
    "\"@\"",
    "\"a\"",
    "<EMPTY_BLANK_NODE>",
    "\"_:\"",
    "\"true\"",
    "\"false\"",
    "\"SELECT\"",
    "\"WHERE\"",
    "\"FILTER\"",
    "<LETTER>",
    "<FULLIRI>",
    "<PNAME_NS>",
    "<PN_LOCAL>",
    "<PNAME_LN>",
    "<PN_PREFIX>",
    "<PN_CHARS_BASE>",
    "<PN_CHARS>",
    "<PN_CHARS_U>",
    "<NODEID>",
    "<ERROR>",
  };

}
