package org.semanticweb.owlapi.api.test;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.AxiomType;
import org.semanticweb.owlapi.model.EntityType;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLObjectProperty;
import org.semanticweb.owlapi.model.OWLObjectPropertyExpression;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyManager;

public class TestNewOntologyImpl {
	static AxiomType<?> Rule=AxiomType.SWRL_RULE;
	static AxiomType<?> AnnotationAssertion=AxiomType.ANNOTATION_ASSERTION;
	static AxiomType<?> DifferentIndividuals=AxiomType.DIFFERENT_INDIVIDUALS;
	static AxiomType<?> DisjointObjectProperties=AxiomType.DISJOINT_OBJECT_PROPERTIES;
	static AxiomType<?> DisjointClasses=AxiomType.DISJOINT_CLASSES;
	static AxiomType<?> EquivalentClasses=AxiomType.EQUIVALENT_CLASSES;
	static AxiomType<?> DisjointDataProperties=AxiomType.DISJOINT_DATA_PROPERTIES;
	static AxiomType<?> EquivalentObjectProperties=AxiomType.EQUIVALENT_OBJECT_PROPERTIES;
	static AxiomType<?> EquivalentDataProperties=AxiomType.EQUIVALENT_DATA_PROPERTIES;

	static AxiomType<?> HasKey=AxiomType.HAS_KEY;
	static OWLDataFactory f=OWLManager.getOWLDataFactory();
	static EntityType Class=EntityType.CLASS;
	static EntityType Datatype=EntityType.DATATYPE;
	static EntityType DataProperty=EntityType.DATA_PROPERTY;

	public static void execute(OWLOntology o1, OWLClass A, OWLObjectProperty p,
			OWLObjectPropertyExpression inv) throws Exception {
		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getAxiomCount(Rule));
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getAnnotationAssertionAxioms(IRI.create("http://www.w3.org/2000/01/rdf-schema#Literal")));
		System.out.println(o1.getDeclarationAxioms(f.getOWLEntity(Datatype, IRI.create("http://www.w3.org/2000/01/rdf-schema#Literal"))));
		System.out.println(o1.getDatatypeDefinitions(f.getOWLDatatype(IRI.create("http://www.w3.org/2000/01/rdf-schema#Literal"))));
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getAnnotationAssertionAxioms(IRI.create("http://www.example.org/ISA14#wrotePhDThesis")));
		System.out.println(o1.getDeclarationAxioms(f.getOWLEntity(DataProperty, IRI.create("http://www.example.org/ISA14#wrotePhDThesis"))));
		System.out.println(o1.getAxioms(f.getOWLDataProperty(IRI.create("http://www.example.org/ISA14#wrotePhDThesis"))));
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getAnnotationAssertionAxioms(IRI.create("http://www.example.org/ISA14#Researcher")));
		System.out.println(o1.getDeclarationAxioms(f.getOWLEntity(Class, IRI.create("http://www.example.org/ISA14#Researcher"))));
		System.out.println(o1.getAxioms(f.getOWLClass(IRI.create("http://www.example.org/ISA14#Researcher"))));
		System.out.println(o1.getAxioms(HasKey));
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getReferencedAnonymousIndividuals());
		System.out.println(o1.getAxioms(AnnotationAssertion));
		System.out.println(o1.getGeneralClassAxioms());
		System.out.println(o1.getAxioms(DifferentIndividuals));
		System.out.println(o1.getAxioms(DisjointClasses));
		System.out.println(o1.getAxioms(DisjointObjectProperties));
		System.out.println(o1.getAxioms(DisjointDataProperties));
		System.out.println(o1.getAxioms(HasKey));
		System.out.println(o1.getAxioms(Rule));
		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getAxioms());
		System.out.println(o1.getAxioms());

		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getAxioms());
		System.out.println(o1.getAxioms());
		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getDeclarationAxioms(f.getOWLEntity(Class, IRI.create("http://www.example.org/ISA14#Researcher"))));
		System.out.println(o1.getAnnotationAssertionAxioms(IRI.create("http://www.example.org/ISA14#Researcher")));
		System.out.println(o1.getAxioms(f.getOWLClass(IRI.create("http://www.example.org/ISA14#Researcher"))));
		System.out.println(o1.getDeclarationAxioms(f.getOWLEntity(DataProperty, IRI.create("http://www.example.org/ISA14#wrotePhDThesis"))));
		System.out.println(o1.getAnnotationAssertionAxioms(IRI.create("http://www.example.org/ISA14#wrotePhDThesis")));
		System.out.println(o1.getAxioms(f.getOWLDataProperty(IRI.create("http://www.example.org/ISA14#wrotePhDThesis"))));
		System.out.println(o1.getDeclarationAxioms(f.getOWLEntity(Datatype, IRI.create("http://www.w3.org/2000/01/rdf-schema#Literal"))));
		System.out.println(o1.getAnnotationAssertionAxioms(IRI.create("http://www.w3.org/2000/01/rdf-schema#Literal")));
		System.out.println(o1.getAxioms(f.getOWLDatatype(IRI.create("http://www.w3.org/2000/01/rdf-schema#Literal"))));
		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getAxioms());
		System.out.println(o1.getAxioms());
		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getAnnotationAssertionAxioms(IRI.create("http://www.w3.org/2000/01/rdf-schema#Literal")));
		System.out.println(o1.getDeclarationAxioms(f.getOWLEntity(Datatype, IRI.create("http://www.w3.org/2000/01/rdf-schema#Literal"))));
		System.out.println(o1.getDatatypeDefinitions(f.getOWLDatatype(IRI.create("http://www.w3.org/2000/01/rdf-schema#Literal"))));
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getAnnotationAssertionAxioms(IRI.create("http://www.example.org/ISA14#wrotePhDThesis")));
		System.out.println(o1.getDeclarationAxioms(f.getOWLEntity(DataProperty, IRI.create("http://www.example.org/ISA14#wrotePhDThesis"))));
		System.out.println(o1.getAxioms(f.getOWLDataProperty(IRI.create("http://www.example.org/ISA14#wrotePhDThesis"))));
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getAnnotationAssertionAxioms(IRI.create("http://www.example.org/ISA14#Researcher")));
		System.out.println(o1.getDeclarationAxioms(f.getOWLEntity(Class, IRI.create("http://www.example.org/ISA14#Researcher"))));
		System.out.println(o1.getAxioms(f.getOWLClass(IRI.create("http://www.example.org/ISA14#Researcher"))));
		System.out.println(o1.getAxioms(HasKey));
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getReferencedAnonymousIndividuals());
		System.out.println(o1.getAxioms(AnnotationAssertion));
		System.out.println(o1.getGeneralClassAxioms());
		System.out.println(o1.getAxioms(DifferentIndividuals));
		System.out.println(o1.getAxioms(DisjointClasses));
		System.out.println(o1.getAxioms(DisjointObjectProperties));
		System.out.println(o1.getAxioms(DisjointDataProperties));
		System.out.println(o1.getAxioms(HasKey));
		System.out.println(o1.getAxioms(Rule));
		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getAxioms());
		System.out.println(o1.getAxioms());

		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getAnnotationAssertionAxioms(IRI.create("http://www.w3.org/2000/01/rdf-schema#Literal")));
		System.out.println(o1.getDatatypeDefinitions(f.getOWLDatatype(IRI.create("http://www.w3.org/2000/01/rdf-schema#Literal"))));
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getAnnotationAssertionAxioms(IRI.create("http://www.example.org/ISA14#wrotePhDThesis")));
		System.out.println(o1.getFunctionalDataPropertyAxioms(f.getOWLDataProperty(IRI.create("http://www.example.org/ISA14#wrotePhDThesis"))));
		System.out.println(o1.getDataPropertyDomainAxioms(f.getOWLDataProperty(IRI.create("http://www.example.org/ISA14#wrotePhDThesis"))));
		System.out.println(o1.getDataPropertyRangeAxioms(f.getOWLDataProperty(IRI.create("http://www.example.org/ISA14#wrotePhDThesis"))));
		System.out.println(o1.getDataSubPropertyAxiomsForSubProperty(f.getOWLDataProperty(IRI.create("http://www.example.org/ISA14#wrotePhDThesis"))));
		System.out.println(o1.getEquivalentDataPropertiesAxioms(f.getOWLDataProperty(IRI.create("http://www.example.org/ISA14#wrotePhDThesis"))));
		System.out.println(o1.getDisjointDataPropertiesAxioms(f.getOWLDataProperty(IRI.create("http://www.example.org/ISA14#wrotePhDThesis"))));
		System.out.println(o1.getAxioms(Rule));
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getAnnotationAssertionAxioms(IRI.create("http://www.example.org/ISA14#Researcher")));
		System.out.println(o1.getEquivalentClassesAxioms(f.getOWLClass(IRI.create("http://www.example.org/ISA14#Researcher"))));
		System.out.println(o1.getSubClassAxiomsForSubClass(f.getOWLClass(IRI.create("http://www.example.org/ISA14#Researcher"))));
		System.out.println(o1.getDisjointClassesAxioms(f.getOWLClass(IRI.create("http://www.example.org/ISA14#Researcher"))));
		System.out.println(o1.getHasKeyAxioms(f.getOWLClass(IRI.create("http://www.example.org/ISA14#Researcher"))));
		System.out.println(o1.getClassAssertionAxioms(f.getOWLClass(IRI.create("http://www.example.org/ISA14#Researcher"))));
		System.out.println(o1.getAxioms(Rule));
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getReferencedAnonymousIndividuals());
		System.out.println(o1.getAxioms(DisjointClasses));
		System.out.println(o1.getAxioms(EquivalentClasses));
		System.out.println(o1.getAxioms(DisjointObjectProperties));
		System.out.println(o1.getAxioms(EquivalentObjectProperties));
		System.out.println(o1.getAxioms(DisjointDataProperties));
		System.out.println(o1.getAxioms(EquivalentDataProperties));
		System.out.println(o1.getAxioms(DifferentIndividuals));
		System.out.println(o1.getAxioms(Rule));
		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getAnnotationPropertiesInSignature());
		System.out.println(o1.getDataPropertiesInSignature());
		System.out.println(o1.getObjectPropertiesInSignature());
		System.out.println(o1.getClassesInSignature());
		System.out.println(o1.getDatatypesInSignature());
		System.out.println(o1.getIndividualsInSignature());
		System.out.println(o1.getAxioms());
		System.out.println(o1.getAxioms());
	}

	public static void main(String[] args) throws Exception {
		OWLOntologyManager m = Factory.getManager();
		OWLOntology o = m.createOntology();
		OWLDataFactory f = m.getOWLDataFactory();
		final OWLObjectProperty p = f.getOWLObjectProperty(IRI.create("urn:p"));
		final OWLClass A = f.getOWLClass(IRI.create("urn:A"));
		m.addAxiom(o, f.getOWLObjectPropertyDomainAxiom(p.getInverseProperty(), A));
		execute(o, A, p, p.getInverseProperty());
	}
}
