/* Generated By:JavaCC: Do not edit this line. OWLFunctionalSyntaxParserConstants.java */
package org.coode.owl.functionalparser;

public interface OWLFunctionalSyntaxParserConstants {

  int EOF = 0;
  int COMMENT_START = 5;
  int STRING_LITERAL_START = 8;
  int STRINGLITERAL = 10;
  int OPENPAR = 12;
  int CLOSEPAR = 13;
  int COLON = 14;
  int ONTOLOGY = 15;
  int LABEL = 16;
  int IMPORTS = 17;
  int COMMENT = 18;
  int SUBCLASSOF = 19;
  int LANGIDENTIFIER = 20;
  int EQUIVALENTCLASSES = 21;
  int DISJOINTCLASSES = 22;
  int DISJOINTUNION = 23;
  int ANNOTATION = 24;
  int ENTITYANNOTATION = 25;
  int DECLARATION = 26;
  int DOCUMENTATION = 27;
  int CLASS = 28;
  int OBJECTPROP = 29;
  int DATAPROP = 30;
  int INDIVIDUAL = 31;
  int DATATYPE = 32;
  int DATAONEOF = 33;
  int OBJECTONEOF = 34;
  int OBJECTUNIONOF = 35;
  int OBJECTHASVALUE = 36;
  int INVERSEOBJECTPROPERTY = 37;
  int INVERSEOBJECTPROPERTIES = 38;
  int DATACOMPLEMENTOF = 39;
  int DATATYPERESTRICTION = 40;
  int OBJECTINTERSECTIONOF = 41;
  int OBJECTCOMPLEMENTOF = 42;
  int OBJECTALLVALUESFROM = 43;
  int OBJECTSOMEVALUESFROM = 44;
  int OBJECTEXISTSSELF = 45;
  int OBJECTMINCARDINALITY = 46;
  int OBJECTMAXCARDINALITY = 47;
  int OBJECTEXACTCARDINALITY = 48;
  int DATAALLVALUESFROM = 49;
  int DATASOMEVALUESFROM = 50;
  int DATAHASVALUE = 51;
  int DATAEXISTSSELF = 52;
  int DATAMINCARDINALITY = 53;
  int DATAMAXCARDINALITY = 54;
  int DATAEXACTCARDINALITY = 55;
  int SUBOBJECTPROPERTYCHAIN = 56;
  int SUBOBJECTPROPERTYOF = 57;
  int EQUIVALENTOBJECTPROPERTIES = 58;
  int DISJOINTOBJECTPROPERTIES = 59;
  int OBJECTPROPERTYDOMAIN = 60;
  int OBJECTPROPERTYRANGE = 61;
  int FUNCTIONALOBJECTPROPERTY = 62;
  int INVERSEFUNCTIONALOBJECTPROPERTY = 63;
  int REFLEXIVEOBJECTPROPERTY = 64;
  int IRREFLEXIVEOBJECTPROPERTY = 65;
  int SYMMETRICOBJECTPROPERTY = 66;
  int ANTISYMMETRICOBJECTPROPERTY = 67;
  int TRANSITIVEOBJECTPROPERTY = 68;
  int SUBDATAPROPERTYOF = 69;
  int EQUIVALENTDATAPROPERTIES = 70;
  int DISJOINTDATAPROPERTIES = 71;
  int DATAPROPERTYDOMAIN = 72;
  int DATAPROPERTYRANGE = 73;
  int FUNCTIONALDATAPROPERTY = 74;
  int SAMEINDIVIDUALS = 75;
  int DIFFERENTINDIVIDUALS = 76;
  int CLASSASSERTION = 77;
  int OBJECTPROPERTYASSERTION = 78;
  int NEGATIVEOBJECTPROPERTYASSERTION = 79;
  int DATAPROPERTYASSERTION = 80;
  int NEGATIVEDATAPROPERTYASSERTION = 81;
  int NAMESPACE = 82;
  int LENGTH = 83;
  int MINLENGTH = 84;
  int MAXLENGTH = 85;
  int PATTERN = 86;
  int MININCLUSIVE = 87;
  int MAXINCLUSIVE = 88;
  int MINEXCLUSIVE = 89;
  int MAXEXCLUSIVE = 90;
  int TOTALDIGITS = 91;
  int FRACTIONDIGITS = 92;
  int EQUALS = 93;
  int INT = 94;
  int QURI = 95;
  int NCNAME1 = 96;
  int NCCHAR_FULL = 97;
  int NCCHAR1 = 98;
  int ERROR = 99;

  int DEFAULT = 0;
  int IN_COMMENT = 1;
  int IN_STRING_LITERAL = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"//\"",
    "<token of kind 6>",
    "\"\\n\"",
    "\"\\\"\"",
    "\"\\\\\\\"\"",
    "\"\\\"\"",
    "<token of kind 11>",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"Ontology\"",
    "\"Label\"",
    "\"Import\"",
    "\"Comment\"",
    "\"SubClassOf\"",
    "\"@\"",
    "\"EquivalentClasses\"",
    "\"DisjointClasses\"",
    "\"DisjointUnion\"",
    "\"Annotation\"",
    "\"EntityAnnotation\"",
    "\"Declaration\"",
    "\"Documentation\"",
    "\"Class\"",
    "\"ObjectProperty\"",
    "\"DataProperty\"",
    "\"NamedIndividual\"",
    "\"Datatype\"",
    "\"DataOneOf\"",
    "\"ObjectOneOf\"",
    "\"ObjectUnionOf\"",
    "\"ObjectHasValue\"",
    "\"InverseObjectProperty\"",
    "\"InverseObjectProperties\"",
    "\"DataComplementOf\"",
    "\"DatatypeRestriction\"",
    "\"ObjectIntersectionOf\"",
    "\"ObjectComplementOf\"",
    "\"ObjectAllValuesFrom\"",
    "\"ObjectSomeValuesFrom\"",
    "\"ObjectExistsSelf\"",
    "\"ObjectMinCardinality\"",
    "\"ObjectMaxCardinality\"",
    "\"ObjectExactCardinality\"",
    "\"DataAllValuesFrom\"",
    "\"DataSomeValuesFrom\"",
    "\"DataHasValue\"",
    "\"DataExistsSelf\"",
    "\"DataMinCardinality\"",
    "\"DataMaxCardinality\"",
    "\"DataExactCardinality\"",
    "\"SubObjectPropertyChain\"",
    "\"SubObjectPropertyOf\"",
    "\"EquivalentObjectProperties\"",
    "\"DisjointObjectProperties\"",
    "\"ObjectPropertyDomain\"",
    "\"ObjectPropertyRange\"",
    "\"FunctionalObjectProperty\"",
    "\"InverseFunctionalObjectProperty\"",
    "\"ReflexiveObjectProperty\"",
    "\"IrreflexiveObjectProperty\"",
    "\"SymmetricObjectProperty\"",
    "\"AntiSymmetricObjectProperty\"",
    "\"TransitiveObjectProperty\"",
    "\"SubDataPropertyOf\"",
    "\"EquivalentDataProperties\"",
    "\"DisjointDataProperties\"",
    "\"DataPropertyDomain\"",
    "\"DataPropertyRange\"",
    "\"FunctionalDataProperty\"",
    "\"SameIndividuals\"",
    "\"DifferentIndividuals\"",
    "\"ClassAssertion\"",
    "\"ObjectPropertyAssertion\"",
    "\"NegativeObjectPropertyAssertion\"",
    "\"DataPropertyAssertion\"",
    "\"NegativeDataPropertyAssertion\"",
    "\"Namespace\"",
    "\"length\"",
    "\"minLength\"",
    "\"maxLength\"",
    "\"pattern\"",
    "\"minInclusive\"",
    "\"maxInclusive\"",
    "\"minExclusive\"",
    "\"maxExclusive\"",
    "\"totalDigits\"",
    "\"fractionDigits\"",
    "\"=\"",
    "<INT>",
    "<QURI>",
    "<NCNAME1>",
    "<NCCHAR_FULL>",
    "<NCCHAR1>",
    "<ERROR>",
    "\"^^\"",
  };

}
