/* Generated By:JavaCC: Do not edit this line. DLSyntaxParserConstants.java */
package uk.ac.manchester.cs.owl.dlsyntax.parser;

public interface DLSyntaxParserConstants {

  int EOF = 0;
  int SUBCLASSOF = 4;
  int EQUIVALENTTO = 5;
  int NEQ = 6;
  int COMPOSE = 7;
  int DOT = 8;
  int INVERSE = 9;
  int OPENPAR = 10;
  int CLOSEPAR = 11;
  int OPENSQPAR = 12;
  int CLOSESQPAR = 13;
  int OPENBRACE = 14;
  int CLOSEBRACE = 15;
  int COLON = 16;
  int AND = 17;
  int OR = 18;
  int NOT = 19;
  int SOME = 20;
  int ALL = 21;
  int MIN = 22;
  int MAX = 23;
  int EXACT = 24;
  int IN = 25;
  int TRANSITIVEROLES = 26;
  int INT = 27;
  int DOUBLE = 28;
  int ID = 29;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<SUBCLASSOF>",
    "<EQUIVALENTTO>",
    "<NEQ>",
    "<COMPOSE>",
    "\".\"",
    "<INVERSE>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<SOME>",
    "<ALL>",
    "<MIN>",
    "<MAX>",
    "<EXACT>",
    "<IN>",
    "<TRANSITIVEROLES>",
    "<INT>",
    "<DOUBLE>",
    "<ID>",
    "\"\\n\"",
    "\",\"",
  };

}
