/* Generated By:JavaCC: Do not edit this line. TurtleParserConstants.java */
package uk.ac.manchester.cs.owl.turtle.parser;

public interface TurtleParserConstants {

  int EOF = 0;
  int COMMENT = 5;
  int STRING = 9;
  int LONG_STRING = 13;
  int DIGIT = 14;
  int INTEGER = 15;
  int DOUBLE = 16;
  int DECIMAL = 17;
  int EXPONENT = 18;
  int OPENPAR = 19;
  int CLOSEPAR = 20;
  int COMMA = 21;
  int DOT = 22;
  int SEMICOLON = 23;
  int PREFIX = 24;
  int DOUBLE_CARET = 25;
  int BASE = 26;
  int AT = 27;
  int A = 28;
  int EMPTY_BLANK_NODE = 29;
  int OPEN_SQUARE_BRACKET = 30;
  int CLOSE_SQUARE_BRACKET = 31;
  int NODE_ID_START = 32;
  int TRUE = 33;
  int FALSE = 34;
  int SELECT = 35;
  int WHERE = 36;
  int FILTER = 37;
  int LETTER = 38;
  int FULLIRI = 39;
  int PNAME_NS = 40;
  int PN_LOCAL = 41;
  int PNAME_LN = 42;
  int PN_PREFIX = 43;
  int PN_CHARS_BASE = 44;
  int PN_CHARS = 45;
  int PN_CHARS_U = 46;
  int NODEID = 47;
  int ERROR = 48;

  int DEFAULT = 0;
  int IN_STRING = 1;
  int IN_LONG_STRING = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"\\\"\"",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"\\\"\"",
    "\"\\\"\\\"\\\"\"",
    "<token of kind 11>",
    "<token of kind 12>",
    "\"\\\"\\\"\\\"\"",
    "<DIGIT>",
    "<INTEGER>",
    "<DOUBLE>",
    "<DECIMAL>",
    "<EXPONENT>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"@prefix\"",
    "\"^^\"",
    "\"@base\"",
    "\"@\"",
    "\"a\"",
    "\"[]\"",
    "\"[\"",
    "\"]\"",
    "\"_:\"",
    "\"true\"",
    "\"false\"",
    "\"SELECT\"",
    "\"WHERE\"",
    "\"FILTER\"",
    "<LETTER>",
    "<FULLIRI>",
    "<PNAME_NS>",
    "<PN_LOCAL>",
    "<PNAME_LN>",
    "<PN_PREFIX>",
    "<PN_CHARS_BASE>",
    "<PN_CHARS>",
    "<PN_CHARS_U>",
    "<NODEID>",
    "<ERROR>",
  };

}
