/* Generated By:JavaCC: Do not edit this line. OBOParserConstants.java */
package org.coode.owlapi.obo.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OBOParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VALUE_START = 6;
  /** RegularExpression Id. */
  int VALUE_END = 7;
  /** RegularExpression Id. */
  int OPEN_SQUARE_BRACKET = 9;
  /** RegularExpression Id. */
  int CLOSE_SQUARE_BRACKET = 10;
  /** RegularExpression Id. */
  int CHAR = 11;
  /** RegularExpression Id. */
  int STRING = 12;
  /** RegularExpression Id. */
  int ERROR = 13;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_VALUE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\":\"",
    "\"\\n\"",
    "<token of kind 8>",
    "\"[\"",
    "\"]\"",
    "<CHAR>",
    "<STRING>",
    "<ERROR>",
  };

}
