package org.semanticweb.owlapi.api.test;

import static org.junit.Assert.assertEquals;
import static org.semanticweb.owlapi.utility.Construct.ATOMNEG;
import static org.semanticweb.owlapi.utility.Construct.C;
import static org.semanticweb.owlapi.utility.Construct.CINT;
import static org.semanticweb.owlapi.utility.Construct.D;
import static org.semanticweb.owlapi.utility.Construct.E;
import static org.semanticweb.owlapi.utility.Construct.F;
import static org.semanticweb.owlapi.utility.Construct.H;
import static org.semanticweb.owlapi.utility.Construct.I;
import static org.semanticweb.owlapi.utility.Construct.LIMEXIST;
import static org.semanticweb.owlapi.utility.Construct.N;
import static org.semanticweb.owlapi.utility.Construct.O;
import static org.semanticweb.owlapi.utility.Construct.Q;
import static org.semanticweb.owlapi.utility.Construct.R;
import static org.semanticweb.owlapi.utility.Construct.RRESTR;
import static org.semanticweb.owlapi.utility.Construct.Rr;
import static org.semanticweb.owlapi.utility.Construct.TRAN;
import static org.semanticweb.owlapi.utility.Construct.U;
import static org.semanticweb.owlapi.utility.Construct.UNIVRESTR;
import static org.semanticweb.owlapi.utility.Languages.AL;
import static org.semanticweb.owlapi.utility.Languages.ALC;
import static org.semanticweb.owlapi.utility.Languages.ALCD;
import static org.semanticweb.owlapi.utility.Languages.ALCF;
import static org.semanticweb.owlapi.utility.Languages.ALCFD;
import static org.semanticweb.owlapi.utility.Languages.ALCH;
import static org.semanticweb.owlapi.utility.Languages.ALCHD;
import static org.semanticweb.owlapi.utility.Languages.ALCHF;
import static org.semanticweb.owlapi.utility.Languages.ALCHFD;
import static org.semanticweb.owlapi.utility.Languages.ALCHI;
import static org.semanticweb.owlapi.utility.Languages.ALCHID;
import static org.semanticweb.owlapi.utility.Languages.ALCHIF;
import static org.semanticweb.owlapi.utility.Languages.ALCHIFD;
import static org.semanticweb.owlapi.utility.Languages.ALCHIN;
import static org.semanticweb.owlapi.utility.Languages.ALCHIND;
import static org.semanticweb.owlapi.utility.Languages.ALCHIQ;
import static org.semanticweb.owlapi.utility.Languages.ALCHIQD;
import static org.semanticweb.owlapi.utility.Languages.ALCHN;
import static org.semanticweb.owlapi.utility.Languages.ALCHND;
import static org.semanticweb.owlapi.utility.Languages.ALCHO;
import static org.semanticweb.owlapi.utility.Languages.ALCHOD;
import static org.semanticweb.owlapi.utility.Languages.ALCHOF;
import static org.semanticweb.owlapi.utility.Languages.ALCHOFD;
import static org.semanticweb.owlapi.utility.Languages.ALCHOI;
import static org.semanticweb.owlapi.utility.Languages.ALCHOID;
import static org.semanticweb.owlapi.utility.Languages.ALCHOIF;
import static org.semanticweb.owlapi.utility.Languages.ALCHOIFD;
import static org.semanticweb.owlapi.utility.Languages.ALCHOIN;
import static org.semanticweb.owlapi.utility.Languages.ALCHOIND;
import static org.semanticweb.owlapi.utility.Languages.ALCHOIQ;
import static org.semanticweb.owlapi.utility.Languages.ALCHOIQD;
import static org.semanticweb.owlapi.utility.Languages.ALCHON;
import static org.semanticweb.owlapi.utility.Languages.ALCHOND;
import static org.semanticweb.owlapi.utility.Languages.ALCHOQ;
import static org.semanticweb.owlapi.utility.Languages.ALCHOQD;
import static org.semanticweb.owlapi.utility.Languages.ALCHQ;
import static org.semanticweb.owlapi.utility.Languages.ALCHQD;
import static org.semanticweb.owlapi.utility.Languages.ALCI;
import static org.semanticweb.owlapi.utility.Languages.ALCID;
import static org.semanticweb.owlapi.utility.Languages.ALCIF;
import static org.semanticweb.owlapi.utility.Languages.ALCIFD;
import static org.semanticweb.owlapi.utility.Languages.ALCIN;
import static org.semanticweb.owlapi.utility.Languages.ALCIND;
import static org.semanticweb.owlapi.utility.Languages.ALCIQ;
import static org.semanticweb.owlapi.utility.Languages.ALCIQD;
import static org.semanticweb.owlapi.utility.Languages.ALCN;
import static org.semanticweb.owlapi.utility.Languages.ALCND;
import static org.semanticweb.owlapi.utility.Languages.ALCO;
import static org.semanticweb.owlapi.utility.Languages.ALCOD;
import static org.semanticweb.owlapi.utility.Languages.ALCOF;
import static org.semanticweb.owlapi.utility.Languages.ALCOFD;
import static org.semanticweb.owlapi.utility.Languages.ALCOI;
import static org.semanticweb.owlapi.utility.Languages.ALCOID;
import static org.semanticweb.owlapi.utility.Languages.ALCOIF;
import static org.semanticweb.owlapi.utility.Languages.ALCOIFD;
import static org.semanticweb.owlapi.utility.Languages.ALCOIN;
import static org.semanticweb.owlapi.utility.Languages.ALCOIND;
import static org.semanticweb.owlapi.utility.Languages.ALCOIQ;
import static org.semanticweb.owlapi.utility.Languages.ALCOIQD;
import static org.semanticweb.owlapi.utility.Languages.ALCON;
import static org.semanticweb.owlapi.utility.Languages.ALCOND;
import static org.semanticweb.owlapi.utility.Languages.ALCOQ;
import static org.semanticweb.owlapi.utility.Languages.ALCOQD;
import static org.semanticweb.owlapi.utility.Languages.ALCQ;
import static org.semanticweb.owlapi.utility.Languages.ALCQD;
import static org.semanticweb.owlapi.utility.Languages.ALCR;
import static org.semanticweb.owlapi.utility.Languages.ALCRD;
import static org.semanticweb.owlapi.utility.Languages.ALCRF;
import static org.semanticweb.owlapi.utility.Languages.ALCRFD;
import static org.semanticweb.owlapi.utility.Languages.ALCRI;
import static org.semanticweb.owlapi.utility.Languages.ALCRID;
import static org.semanticweb.owlapi.utility.Languages.ALCRIF;
import static org.semanticweb.owlapi.utility.Languages.ALCRIFD;
import static org.semanticweb.owlapi.utility.Languages.ALCRIN;
import static org.semanticweb.owlapi.utility.Languages.ALCRIND;
import static org.semanticweb.owlapi.utility.Languages.ALCRIQ;
import static org.semanticweb.owlapi.utility.Languages.ALCRIQD;
import static org.semanticweb.owlapi.utility.Languages.ALCRN;
import static org.semanticweb.owlapi.utility.Languages.ALCRND;
import static org.semanticweb.owlapi.utility.Languages.ALCRO;
import static org.semanticweb.owlapi.utility.Languages.ALCROD;
import static org.semanticweb.owlapi.utility.Languages.ALCROF;
import static org.semanticweb.owlapi.utility.Languages.ALCROFD;
import static org.semanticweb.owlapi.utility.Languages.ALCROI;
import static org.semanticweb.owlapi.utility.Languages.ALCROID;
import static org.semanticweb.owlapi.utility.Languages.ALCROIF;
import static org.semanticweb.owlapi.utility.Languages.ALCROIFD;
import static org.semanticweb.owlapi.utility.Languages.ALCROIN;
import static org.semanticweb.owlapi.utility.Languages.ALCROIND;
import static org.semanticweb.owlapi.utility.Languages.ALCROIQ;
import static org.semanticweb.owlapi.utility.Languages.ALCROIQD;
import static org.semanticweb.owlapi.utility.Languages.ALCRON;
import static org.semanticweb.owlapi.utility.Languages.ALCROND;
import static org.semanticweb.owlapi.utility.Languages.ALCROQ;
import static org.semanticweb.owlapi.utility.Languages.ALCROQD;
import static org.semanticweb.owlapi.utility.Languages.ALCRQ;
import static org.semanticweb.owlapi.utility.Languages.ALCRQD;
import static org.semanticweb.owlapi.utility.Languages.ALCRr;
import static org.semanticweb.owlapi.utility.Languages.ALCRrD;
import static org.semanticweb.owlapi.utility.Languages.ALCRrF;
import static org.semanticweb.owlapi.utility.Languages.ALCRrFD;
import static org.semanticweb.owlapi.utility.Languages.ALCRrN;
import static org.semanticweb.owlapi.utility.Languages.ALCRrND;
import static org.semanticweb.owlapi.utility.Languages.ALCRrO;
import static org.semanticweb.owlapi.utility.Languages.ALCRrOD;
import static org.semanticweb.owlapi.utility.Languages.ALCRrOF;
import static org.semanticweb.owlapi.utility.Languages.ALCRrOFD;
import static org.semanticweb.owlapi.utility.Languages.ALCRrON;
import static org.semanticweb.owlapi.utility.Languages.ALCRrOND;
import static org.semanticweb.owlapi.utility.Languages.ALCRrOQ;
import static org.semanticweb.owlapi.utility.Languages.ALCRrOQD;
import static org.semanticweb.owlapi.utility.Languages.ALCRrQ;
import static org.semanticweb.owlapi.utility.Languages.ALCRrQD;
import static org.semanticweb.owlapi.utility.Languages.ALE;
import static org.semanticweb.owlapi.utility.Languages.EL;
import static org.semanticweb.owlapi.utility.Languages.ELPLUSPLUS;
import static org.semanticweb.owlapi.utility.Languages.FL;
import static org.semanticweb.owlapi.utility.Languages.FL0;
import static org.semanticweb.owlapi.utility.Languages.FLMINUS;
import static org.semanticweb.owlapi.utility.Languages.S;
import static org.semanticweb.owlapi.utility.Languages.SD;
import static org.semanticweb.owlapi.utility.Languages.SF;
import static org.semanticweb.owlapi.utility.Languages.SFD;
import static org.semanticweb.owlapi.utility.Languages.SH;
import static org.semanticweb.owlapi.utility.Languages.SHD;
import static org.semanticweb.owlapi.utility.Languages.SHF;
import static org.semanticweb.owlapi.utility.Languages.SHFD;
import static org.semanticweb.owlapi.utility.Languages.SHI;
import static org.semanticweb.owlapi.utility.Languages.SHID;
import static org.semanticweb.owlapi.utility.Languages.SHIF;
import static org.semanticweb.owlapi.utility.Languages.SHIFD;
import static org.semanticweb.owlapi.utility.Languages.SHIN;
import static org.semanticweb.owlapi.utility.Languages.SHIND;
import static org.semanticweb.owlapi.utility.Languages.SHIQ;
import static org.semanticweb.owlapi.utility.Languages.SHIQD;
import static org.semanticweb.owlapi.utility.Languages.SHN;
import static org.semanticweb.owlapi.utility.Languages.SHND;
import static org.semanticweb.owlapi.utility.Languages.SHO;
import static org.semanticweb.owlapi.utility.Languages.SHOD;
import static org.semanticweb.owlapi.utility.Languages.SHOF;
import static org.semanticweb.owlapi.utility.Languages.SHOFD;
import static org.semanticweb.owlapi.utility.Languages.SHOI;
import static org.semanticweb.owlapi.utility.Languages.SHOID;
import static org.semanticweb.owlapi.utility.Languages.SHOIF;
import static org.semanticweb.owlapi.utility.Languages.SHOIFD;
import static org.semanticweb.owlapi.utility.Languages.SHOIN;
import static org.semanticweb.owlapi.utility.Languages.SHOIND;
import static org.semanticweb.owlapi.utility.Languages.SHOIQ;
import static org.semanticweb.owlapi.utility.Languages.SHOIQD;
import static org.semanticweb.owlapi.utility.Languages.SHON;
import static org.semanticweb.owlapi.utility.Languages.SHOND;
import static org.semanticweb.owlapi.utility.Languages.SHOQ;
import static org.semanticweb.owlapi.utility.Languages.SHOQD;
import static org.semanticweb.owlapi.utility.Languages.SHQ;
import static org.semanticweb.owlapi.utility.Languages.SHQD;
import static org.semanticweb.owlapi.utility.Languages.SI;
import static org.semanticweb.owlapi.utility.Languages.SID;
import static org.semanticweb.owlapi.utility.Languages.SIF;
import static org.semanticweb.owlapi.utility.Languages.SIFD;
import static org.semanticweb.owlapi.utility.Languages.SIN;
import static org.semanticweb.owlapi.utility.Languages.SIND;
import static org.semanticweb.owlapi.utility.Languages.SIQ;
import static org.semanticweb.owlapi.utility.Languages.SIQD;
import static org.semanticweb.owlapi.utility.Languages.SN;
import static org.semanticweb.owlapi.utility.Languages.SND;
import static org.semanticweb.owlapi.utility.Languages.SO;
import static org.semanticweb.owlapi.utility.Languages.SOD;
import static org.semanticweb.owlapi.utility.Languages.SOF;
import static org.semanticweb.owlapi.utility.Languages.SOFD;
import static org.semanticweb.owlapi.utility.Languages.SOI;
import static org.semanticweb.owlapi.utility.Languages.SOID;
import static org.semanticweb.owlapi.utility.Languages.SOIF;
import static org.semanticweb.owlapi.utility.Languages.SOIFD;
import static org.semanticweb.owlapi.utility.Languages.SOIN;
import static org.semanticweb.owlapi.utility.Languages.SOIND;
import static org.semanticweb.owlapi.utility.Languages.SOIQ;
import static org.semanticweb.owlapi.utility.Languages.SOIQD;
import static org.semanticweb.owlapi.utility.Languages.SON;
import static org.semanticweb.owlapi.utility.Languages.SOND;
import static org.semanticweb.owlapi.utility.Languages.SOQ;
import static org.semanticweb.owlapi.utility.Languages.SOQD;
import static org.semanticweb.owlapi.utility.Languages.SQ;
import static org.semanticweb.owlapi.utility.Languages.SQD;
import static org.semanticweb.owlapi.utility.Languages.SR;
import static org.semanticweb.owlapi.utility.Languages.SRD;
import static org.semanticweb.owlapi.utility.Languages.SRF;
import static org.semanticweb.owlapi.utility.Languages.SRFD;
import static org.semanticweb.owlapi.utility.Languages.SRI;
import static org.semanticweb.owlapi.utility.Languages.SRID;
import static org.semanticweb.owlapi.utility.Languages.SRIF;
import static org.semanticweb.owlapi.utility.Languages.SRIFD;
import static org.semanticweb.owlapi.utility.Languages.SRIN;
import static org.semanticweb.owlapi.utility.Languages.SRIND;
import static org.semanticweb.owlapi.utility.Languages.SRIQ;
import static org.semanticweb.owlapi.utility.Languages.SRIQD;
import static org.semanticweb.owlapi.utility.Languages.SRN;
import static org.semanticweb.owlapi.utility.Languages.SRND;
import static org.semanticweb.owlapi.utility.Languages.SRO;
import static org.semanticweb.owlapi.utility.Languages.SROD;
import static org.semanticweb.owlapi.utility.Languages.SROF;
import static org.semanticweb.owlapi.utility.Languages.SROFD;
import static org.semanticweb.owlapi.utility.Languages.SROI;
import static org.semanticweb.owlapi.utility.Languages.SROID;
import static org.semanticweb.owlapi.utility.Languages.SROIF;
import static org.semanticweb.owlapi.utility.Languages.SROIFD;
import static org.semanticweb.owlapi.utility.Languages.SROIN;
import static org.semanticweb.owlapi.utility.Languages.SROIND;
import static org.semanticweb.owlapi.utility.Languages.SROIQ;
import static org.semanticweb.owlapi.utility.Languages.SROIQD;
import static org.semanticweb.owlapi.utility.Languages.SRON;
import static org.semanticweb.owlapi.utility.Languages.SROND;
import static org.semanticweb.owlapi.utility.Languages.SROQ;
import static org.semanticweb.owlapi.utility.Languages.SROQD;
import static org.semanticweb.owlapi.utility.Languages.SRQ;
import static org.semanticweb.owlapi.utility.Languages.SRQD;
import static org.semanticweb.owlapi.utility.Languages.SRr;
import static org.semanticweb.owlapi.utility.Languages.SRrD;
import static org.semanticweb.owlapi.utility.Languages.SRrF;
import static org.semanticweb.owlapi.utility.Languages.SRrFD;
import static org.semanticweb.owlapi.utility.Languages.SRrN;
import static org.semanticweb.owlapi.utility.Languages.SRrND;
import static org.semanticweb.owlapi.utility.Languages.SRrO;
import static org.semanticweb.owlapi.utility.Languages.SRrOD;
import static org.semanticweb.owlapi.utility.Languages.SRrOF;
import static org.semanticweb.owlapi.utility.Languages.SRrOFD;
import static org.semanticweb.owlapi.utility.Languages.SRrON;
import static org.semanticweb.owlapi.utility.Languages.SRrOND;
import static org.semanticweb.owlapi.utility.Languages.SRrOQ;
import static org.semanticweb.owlapi.utility.Languages.SRrOQD;
import static org.semanticweb.owlapi.utility.Languages.SRrQ;
import static org.semanticweb.owlapi.utility.Languages.SRrQD;

import java.util.Arrays;
import java.util.EnumSet;
import java.util.List;
import java.util.stream.Collectors;

import org.junit.Test;
import org.semanticweb.owlapi.utility.Construct;
import org.semanticweb.owlapi.utility.Languages;

@SuppressWarnings("javadoc")
public class LanguagesTestCase {
    private static EnumSet<Construct> set(Construct... constructs) {
        return EnumSet.copyOf(Arrays.asList(constructs));
    }

    private static void same(Languages l, Construct... constructs) {
        assertEquals(set(constructs), l.components());
    }

    @Test
    public void shouldFindExpectedConstructs() {
        same(FL0, CINT, UNIVRESTR);
        same(FLMINUS, CINT, UNIVRESTR, LIMEXIST);
        same(FL, RRESTR, CINT, UNIVRESTR, LIMEXIST);
        same(AL, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(EL, RRESTR, E, CINT);
        same(ALE, E, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALC, RRESTR, C, U, E, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(S, RRESTR, C, U, E, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCD, RRESTR, C, U, E, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCF, RRESTR, C, U, E, F, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCFD, RRESTR, C, U, E, F, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCN, RRESTR, C, U, E, N, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCND, RRESTR, C, U, E, N, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCQ, RRESTR, C, U, E, Q, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCQD, RRESTR, C, U, E, Q, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCI, RRESTR, C, U, E, I, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCID, RRESTR, C, U, E, I, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCIF, RRESTR, C, U, E, I, F, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCIFD, RRESTR, C, U, E, I, F, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCIN, RRESTR, C, U, E, I, N, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCIND, RRESTR, C, U, E, I, N, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCIQ, RRESTR, C, U, E, I, Q, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCIQD, RRESTR, C, U, E, I, Q, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCO, RRESTR, C, U, E, O, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCOD, RRESTR, C, U, E, O, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCOF, RRESTR, C, U, E, O, F, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCOFD, RRESTR, C, U, E, O, F, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCON, RRESTR, C, U, E, O, N, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCOND, RRESTR, C, U, E, O, N, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCOQ, RRESTR, C, U, E, O, Q, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCOQD, RRESTR, C, U, E, O, Q, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCOI, RRESTR, C, U, E, O, I, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCOID, RRESTR, C, U, E, O, I, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCOIF, RRESTR, C, U, E, O, I, F, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCOIFD, RRESTR, C, U, E, O, I, F, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCOIN, RRESTR, C, U, E, O, I, N, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCOIND, RRESTR, C, U, E, O, I, N, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCOIQ, RRESTR, C, U, E, O, I, Q, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCOIQD, RRESTR, C, U, E, O, I, Q, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCH, RRESTR, C, U, E, H, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHD, RRESTR, C, U, E, H, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHF, RRESTR, C, U, E, H, F, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHFD, RRESTR, C, U, E, H, F, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHN, RRESTR, C, U, E, H, N, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHND, RRESTR, C, U, E, H, N, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHQ, RRESTR, C, U, E, H, Q, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHQD, RRESTR, C, U, E, H, Q, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHI, RRESTR, C, U, E, H, I, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHID, RRESTR, C, U, E, H, I, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHIF, RRESTR, C, U, E, H, I, F, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHIFD, RRESTR, C, U, E, H, I, F, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHIN, RRESTR, C, U, E, H, I, N, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHIND, RRESTR, C, U, E, H, I, N, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHIQ, RRESTR, C, U, E, H, I, Q, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHIQD, RRESTR, C, U, E, H, I, Q, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHO, RRESTR, C, U, E, H, O, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHOD, RRESTR, C, U, E, H, O, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHOF, RRESTR, C, U, E, H, O, F, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHOFD, RRESTR, C, U, E, H, O, F, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHON, RRESTR, C, U, E, H, O, N, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHOND, RRESTR, C, U, E, H, O, N, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHOQ, RRESTR, C, U, E, H, O, Q, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHOQD, RRESTR, C, U, E, H, O, Q, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHOI, RRESTR, C, U, E, H, O, I, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHOID, RRESTR, C, U, E, H, O, I, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHOIF, RRESTR, C, U, E, H, O, I, F, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHOIFD, RRESTR, C, U, E, H, O, I, F, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHOIN, RRESTR, C, U, E, H, O, I, N, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHOIND, RRESTR, C, U, E, H, O, I, N, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHOIQ, RRESTR, C, U, E, H, O, I, Q, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCHOIQD, RRESTR, C, U, E, H, O, I, Q, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRr, RRESTR, C, U, E, Rr, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrD, RRESTR, C, U, E, Rr, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrF, RRESTR, C, U, E, Rr, F, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrFD, RRESTR, C, U, E, Rr, F, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrN, RRESTR, C, U, E, Rr, N, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrND, RRESTR, C, U, E, Rr, N, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrQ, RRESTR, C, U, E, Rr, Q, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrQD, RRESTR, C, U, E, Rr, Q, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrO, RRESTR, C, U, E, Rr, O, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrOD, RRESTR, C, U, E, Rr, O, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrOF, RRESTR, C, U, E, Rr, O, F, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrOFD, RRESTR, C, U, E, Rr, O, F, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrON, RRESTR, C, U, E, Rr, O, N, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrOND, RRESTR, C, U, E, Rr, O, N, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrOQ, RRESTR, C, U, E, Rr, O, Q, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRrOQD, RRESTR, C, U, E, Rr, O, Q, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCR, RRESTR, C, U, E, R, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRD, RRESTR, C, U, E, R, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRF, RRESTR, C, U, E, R, F, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRFD, RRESTR, C, U, E, R, F, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRN, RRESTR, C, U, E, R, N, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRND, RRESTR, C, U, E, R, N, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRQ, RRESTR, C, U, E, R, Q, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRQD, RRESTR, C, U, E, R, Q, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRI, RRESTR, C, U, E, R, I, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRID, RRESTR, C, U, E, R, I, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRIF, RRESTR, C, U, E, R, I, F, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRIFD, RRESTR, C, U, E, R, I, F, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRIN, RRESTR, C, U, E, R, I, N, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRIND, RRESTR, C, U, E, R, I, N, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRIQ, RRESTR, C, U, E, R, I, Q, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRIQD, RRESTR, C, U, E, R, I, Q, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRO, RRESTR, C, U, E, R, O, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCROD, RRESTR, C, U, E, R, O, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCROF, RRESTR, C, U, E, R, O, F, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCROFD, RRESTR, C, U, E, R, O, F, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCRON, RRESTR, C, U, E, R, O, N, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCROND, RRESTR, C, U, E, R, O, N, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCROQ, RRESTR, C, U, E, R, O, Q, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCROQD, RRESTR, C, U, E, R, O, Q, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCROI, RRESTR, C, U, E, R, O, I, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCROID, RRESTR, C, U, E, R, O, I, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCROIF, RRESTR, C, U, E, R, O, I, F, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCROIFD, RRESTR, C, U, E, R, O, I, F, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCROIN, RRESTR, C, U, E, R, O, I, N, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCROIND, RRESTR, C, U, E, R, O, I, N, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCROIQ, RRESTR, C, U, E, R, O, I, Q, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ALCROIQD, RRESTR, C, U, E, R, O, I, Q, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SD, RRESTR, C, U, E, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SF, RRESTR, C, U, E, F, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SFD, RRESTR, C, U, E, F, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SN, RRESTR, C, U, E, N, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SND, RRESTR, C, U, E, N, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SQ, RRESTR, C, U, E, Q, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SQD, RRESTR, C, U, E, Q, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SI, RRESTR, C, U, E, I, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SID, RRESTR, C, U, E, I, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SIF, RRESTR, C, U, E, I, F, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SIFD, RRESTR, C, U, E, I, F, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SIN, RRESTR, C, U, E, I, N, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SIND, RRESTR, C, U, E, I, N, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SIQ, RRESTR, C, U, E, I, Q, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SIQD, RRESTR, C, U, E, I, Q, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SO, RRESTR, C, U, E, O, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SOD, RRESTR, C, U, E, O, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SOF, RRESTR, C, U, E, O, F, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SOFD, RRESTR, C, U, E, O, F, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SON, RRESTR, C, U, E, O, N, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SOND, RRESTR, C, U, E, O, N, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SOQ, RRESTR, C, U, E, O, Q, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SOQD, RRESTR, C, U, E, O, Q, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SOI, RRESTR, C, U, E, O, I, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SOID, RRESTR, C, U, E, O, I, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SOIF, RRESTR, C, U, E, O, I, F, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SOIFD, RRESTR, C, U, E, O, I, F, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SOIN, RRESTR, C, U, E, O, I, N, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SOIND, RRESTR, C, U, E, O, I, N, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SOIQ, RRESTR, C, U, E, O, I, Q, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SOIQD, RRESTR, C, U, E, O, I, Q, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SH, RRESTR, C, U, E, H, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHD, RRESTR, C, U, E, H, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHF, RRESTR, C, U, E, H, F, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHFD, RRESTR, C, U, E, H, F, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHN, RRESTR, C, U, E, H, N, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHND, RRESTR, C, U, E, H, N, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHQ, RRESTR, C, U, E, H, Q, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHQD, RRESTR, C, U, E, H, Q, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHI, RRESTR, C, U, E, H, I, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHID, RRESTR, C, U, E, H, I, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHIF, RRESTR, C, U, E, H, I, F, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHIFD, RRESTR, C, U, E, H, I, F, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHIN, RRESTR, C, U, E, H, I, N, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHIND, RRESTR, C, U, E, H, I, N, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHIQ, RRESTR, C, U, E, H, I, Q, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHIQD, RRESTR, C, U, E, H, I, Q, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHO, RRESTR, C, U, E, H, O, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHOD, RRESTR, C, U, E, H, O, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHOF, RRESTR, C, U, E, H, O, F, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHOFD, RRESTR, C, U, E, H, O, F, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHON, RRESTR, C, U, E, H, O, N, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHOND, RRESTR, C, U, E, H, O, N, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHOQ, RRESTR, C, U, E, H, O, Q, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHOQD, RRESTR, C, U, E, H, O, Q, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHOI, RRESTR, C, U, E, H, O, I, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHOID, RRESTR, C, U, E, H, O, I, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHOIF, RRESTR, C, U, E, H, O, I, F, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHOIFD, RRESTR, C, U, E, H, O, I, F, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHOIN, RRESTR, C, U, E, H, O, I, N, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHOIND, RRESTR, C, U, E, H, O, I, N, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHOIQ, RRESTR, C, U, E, H, O, I, Q, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SHOIQD, RRESTR, C, U, E, H, O, I, Q, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRr, RRESTR, C, U, E, Rr, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrD, RRESTR, C, U, E, Rr, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrF, RRESTR, C, U, E, Rr, F, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrFD, RRESTR, C, U, E, Rr, F, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrN, RRESTR, C, U, E, Rr, N, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrND, RRESTR, C, U, E, Rr, N, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrQ, RRESTR, C, U, E, Rr, Q, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrQD, RRESTR, C, U, E, Rr, Q, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrO, RRESTR, C, U, E, Rr, O, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrOD, RRESTR, C, U, E, Rr, O, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrOF, RRESTR, C, U, E, Rr, O, F, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrOFD, RRESTR, C, U, E, Rr, O, F, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrON, RRESTR, C, U, E, Rr, O, N, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrOND, RRESTR, C, U, E, Rr, O, N, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrOQ, RRESTR, C, U, E, Rr, O, Q, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRrOQD, RRESTR, C, U, E, Rr, O, Q, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SR, RRESTR, C, U, E, R, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRD, RRESTR, C, U, E, R, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRF, RRESTR, C, U, E, R, F, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRFD, RRESTR, C, U, E, R, F, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRN, RRESTR, C, U, E, R, N, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRND, RRESTR, C, U, E, R, N, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRQ, RRESTR, C, U, E, R, Q, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRQD, RRESTR, C, U, E, R, Q, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRI, RRESTR, C, U, E, R, I, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRID, RRESTR, C, U, E, R, I, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRIF, RRESTR, C, U, E, R, I, F, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRIFD, RRESTR, C, U, E, R, I, F, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRIN, RRESTR, C, U, E, R, I, N, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRIND, RRESTR, C, U, E, R, I, N, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRIQ, RRESTR, C, U, E, R, I, Q, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRIQD, RRESTR, C, U, E, R, I, Q, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRO, RRESTR, C, U, E, R, O, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SROD, RRESTR, C, U, E, R, O, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SROF, RRESTR, C, U, E, R, O, F, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SROFD, RRESTR, C, U, E, R, O, F, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SRON, RRESTR, C, U, E, R, O, N, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SROND, RRESTR, C, U, E, R, O, N, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SROQ, RRESTR, C, U, E, R, O, Q, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SROQD, RRESTR, C, U, E, R, O, Q, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SROI, RRESTR, C, U, E, R, O, I, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SROID, RRESTR, C, U, E, R, O, I, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SROIF, RRESTR, C, U, E, R, O, I, F, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SROIFD, RRESTR, C, U, E, R, O, I, F, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SROIN, RRESTR, C, U, E, R, O, I, N, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SROIND, RRESTR, C, U, E, R, O, I, N, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SROIQ, RRESTR, C, U, E, R, O, I, Q, TRAN, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(SROIQD, RRESTR, C, U, E, R, O, I, Q, TRAN, D, ATOMNEG, CINT, UNIVRESTR, LIMEXIST);
        same(ELPLUSPLUS, E, R, O, TRAN, D, CINT);
    }

    // utility to write the enum declarations for variations of construct combinations
    public static void dump() {
        // ALC || S (ALC + TRAN)
        // H \subset R
        // O
        // I
        // F \subset N \subset Q
        // D
        for (String s1 : new String[] {"ALC", "S"}) {
            for (String s2 : new String[] {"", "H", "Rr", "R"}) {
                for (String s3 : new String[] {"", "O"}) {
                    for (String s4 : new String[] {"", "I"}) {
                        for (String s5 : new String[] {"", "F", "N", "Q"}) {
                            for (String s6 : new String[] {"", "D"}) {
                                List<String> list = Arrays.asList(s1, s2, s3, s4, s5, s6);
                                String name = list.stream().collect(Collectors.joining());
                                String starter = "    /** " + name + " language. */    ";
                                System.out.println(starter
                                    + name + "(\"" + name + "\"," + list.stream()
                                        .filter(s -> !s.isEmpty()).collect(Collectors.joining(", "))
                                    + "),");
                            }
                        }
                    }
                }
            }
        }
    }

    public static void main(String[] args) {
        for (Languages l : Languages.values()) {
            System.out.println(l.components().stream().map(Construct::name)
                .collect(Collectors.joining(", ", "same(" + l.name() + ", ", ");")));
        }
    }
}
